### ISSUE TITLE
configure does not check some libraries

### ISSUE THREAD

**Issue by noda50** [rcsoccersim/rcsslogplayer#2]
When I install rcsslogplayer, I got the following errors in "make" following "bootstrap" and "configure".

> /usr/bin/ld: cannot find -laudio
/usr/bin/ld: cannot find -lpng
/usr/bin/ld: cannot find -lXi
/usr/bin/ld: cannot find -lXrender
/usr/bin/ld: cannot find -lfreetype
/usr/bin/ld: cannot find -lfontconfig

Should they be checked in configure?

**Comment by herodrigues** [comment]
This project is deprecated. Please use [rcssmonitor](https://github.com/rcsoccersim/rcssmonitor).

@hidehisaakiyama maybe it's a good idea to archive this repository so it'll become read-only.

**Comment by hidehisaakiyama** [comment]
@noda50 
configure can check those libraries, but we need to install additional development packages in order to put symbolic links to the instances of shared library.
If your distribution is ubuntu, try 
```
sudo apt update
sudo apt install build-essential libboost-all-dev qt5-default libfontconfig1-dev libaudio-dev libxt-dev libglib2.0-dev libxi-dev libxrender-dev 
```

As herodrigues says, I recommend rcssmonitor v16 or later instead of rcsslogplayer.
And, I recommend to use CMake.
CMake can link shared libraries without installing each development package.
Please check the latest README.md of rcssmonitor.

**Comment by hidehisaakiyama** [comment]
@herodrigues 
Agree.
Thanks for your suggestion.
